### ISSUE TITLE
SSL_ERROR_BAD_MAC_READ When forwarding SSL port

### ISSUE THREAD

**Issue by null-dev** [aramperes/onetun#22]
I'm getting a strange problem when I attempt to connect to my forwarded GitLab instance using Firefox/Chromium: Some requests are failing with `SSL_ERROR_BAD_MAC_READ`. It also only seems to happen on background requests so I assume it only happens when many requests happen in parallel as the background resources are fetched in parallel.

---

Here's a snapshot of the network log when I try to load GitLab:

![image](https://user-images.githubusercontent.com/9571936/139475984-b0fe09cd-7e43-4d60-85b9-922c8a7d3e76.png)

Notice how the first request for the HTML file executes just fine. Once the browser parses the HTML file however, it fires off a bunch of requests in parallel to grab the script files and the images. A couple of these requests succeed however the rest fail with: `SSL_ERROR_BAD_MAC_READ`.

Also, here's the onetun log (with `--log trace`) corresponding to the above requests: [onetun.log](https://github.com/aramperes/onetun/files/7443821/onetun.log).

---

The issue doesn't happen when I connect directly to the GitLab instance over WireGuard.

**Comment by null-dev** [comment]
Whoops, sorry I should have mentioned that yeah, I am using v0.2.1. Here's some more info if you need it:

```
root@debian:~# onetun --version
onetun 0.2.1
root@debian:~# uname -a
Linux debian 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux
root@debian:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
root@debian:~# cat /etc/onetun/gitlab.conf
ONETUN_ENDPOINT_ADDR=XX.XX.XX.XX:64544
ONETUN_ENDPOINT_PUBLIC_KEY=G9rqZYDFsrrKiSGcJjlhL+FHNlzE29btbLXMB2isPkU=
ONETUN_PRIVATE_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
ONETUN_SOURCE_PEER_IP=10.82.0.2
ONETUN_PORT_FORWARD_1=158.51.98.150:80:10.82.0.3:80:TCP
ONETUN_PORT_FORWARD_2=158.51.98.150:443:10.82.0.3:443:TCP
ONETUN_PORT_FORWARD_3=158.51.98.150:22:10.82.0.3:22:TCP
ONETUN_LOG=trace
```

**Comment by null-dev** [comment]
Also, since the GitLab instance is exposed on the public web anyways, if you want to connect to it to inspect the network requests/responses you can find it here: https://git.svc.vepta.org/

**Comment by aramperes** [comment]
Alright, thanks for all the info! That's pretty unfortunate, I thought I had squashed all the concurrency issues. I have a hunch that it might be because of the lack of `tokio::select!` in the TCP virtual interface, but I will have to investigate.

**Comment by aramperes** [comment]
Hey @null-dev, if you have a chance could you try with onetun `v0.2.4`? It includes some refactoring that should make the tunnel more reliable. I'm hoping it roots out the issue you were having here.

**Comment by null-dev** [comment]
Unfortunately it's still happening. But now it's weird because everything is fine when I switch to trace mode. I suspect that's just because there is reduced parallelism or something as the page loads much slower in trace mode.

I will see if I can get a better reproducer for you tomorrow, I'll try throwing together a docker container that you can run on your local machine.

**Comment by aramperes** [comment]
That's unfortunate. I pushed `v0.2.5` which improves performance at the `trace` level, although in this case, having it reproducible locally would be much more useful so I can pcap. Thanks for the help!

**Comment by null-dev** [comment]
Ok, I've spent the whole day on this and just ended up more confused...

So first of all, the problem occurs when I have the following setup:
![Diagram1](https://user-images.githubusercontent.com/9571936/148672251-05d8c39b-67f9-445d-a5ba-8799bbccd3e5.png)

I've been able to replace GitLab with nginx by just having it serve a fake static GitLab page, so I end up with the following setup:
![Diagram1](https://user-images.githubusercontent.com/9571936/148672333-1a102b35-2c1b-474e-8887-935edd8df561.png)

At this point, the issue is still reproducible. Then I tried running everything on my local machine:
![Diagram1](https://user-images.githubusercontent.com/9571936/148672379-1444993b-fe61-4fb4-a200-bbabb2821858.png)

I was unable to reproduce the issue with this setup however. I also tried injecting fake latency and packet loss (using `tc`) between the browser and onetun to simulate them being on different hosts however I was still unable to reproduce the issue.

So it looks like the issue is only reproducible when onetun is on a different host from the browser.

I also wanted to see if this was just some issue with my browser or network so I replicated the setup in the second diagram using a new server in a different country for "Host A". I then got another server in another country and installed a DE + VNC + Chromium for the "Client". The issue was still reproducible.

---
In this zip file you can find the following:
- A `docker-compose.yml` file along with the corresponding build files in the `server` directory to recreate the docker container shown in the second diagram. It requires that you have wireguard installed on the host machine.
- A script called `onetun.sh` that contains the required settings onetun should be started with to connect to the docker container.

Therefore, with the zip file, you should be able to recreate "Host A" in the scenario shown in the second diagram.

Then from a separate machine, you can connect to "Host A" using your browser (the onetun config in the zip uses port `9443`) and (hopefully) observe the issue.

---

I also already have a functioning "Host A" already setup though (from all the testing I did today) so if you send me your SSH public key I can also give you access to that.

Thanks for looking into this issue!

**Comment by aramperes** [comment]
Thanks for the details. I was able to reproduce your examples with a second machine, so it's not just you setup.

I was able to reproduce the issue with `curl` on one of the files that fails, which will help with pinpointing the issue (browsers have a bunch of other stuff at play like http/2 and keepalive):

```bash
$ curl -k 'https://localhost:9443/assets/application-775f130d36e9eb14cb67c6a63551511b87f78944cebcf6cdddb78292030341df.css' > good.txt
# output: 723198 bytes
# no errors

$ curl -k 'https://naptime.local:9443/assets/application-775f130d36e9eb14cb67c6a63551511b87f78944cebcf6cdddb78292030341df.css' > bad.txt
# output: truncates at 81866 bytes (sometimes a bit more)
# curl: (56) OpenSSL SSL_read: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac, errno 0
```

It seems like some issue with pushing large files over HTTP. The SSL error is saying that the MAC (signature) is not valid since only part of the data was sent.

I'm still unclear as to why it works on `localhost` but not on a remote endpoint. My next step will be to try with the same file but without SSL and see if it's a factor.

**Comment by aramperes** [comment]
I tried without SSL and I can't reproduce the issue, so my guess is that something breaks the MAC check during the data transfer. I'll keep digging.

**Comment by aramperes** [comment]
Here's what I have so far

----

[intercepts.zip](https://github.com/aramperes/onetun/files/7835927/intercepts.zip)

- `local-onetun-server.pcap` == `curl <-> local onetun`
- `local-tunnel.pcap` == `local onetun <-> nginx`
- `remote-onetun-server.pcap` == `curl <-> remote onetun` (with the MAC error)
- `remote-tunnel.pcap` == `remote onetun <-> nginx`
- `tlskey.log` == cURL TLS key log file, can be attached to Wireshark to decrypt TLS

(I recommend setting the `tls` filter in Wireshark)

----

What I first noticed is that the `local-onetun-server` packets are much larger than the ones in `remote-onetun-server`; that's because the MTU (max transmission unit) differs between the interfaces:

- `local-onetun-server (loopback): mtu 65536`
- `remote-onetun-server (ethernet): mtu 1500`
- `local-tunnel / remote-tunnel (wireguard): mtu 1420`

This means that `onetun` breaks down the TLS records differently on both sides (to fit within the MTU). For example, if you look at the structure of the Handshake in each pcap:

**local-onetun-server (mtu 65536):**
```
-> Client Hello
<- Server Hello, Certificate, Server Key Exchange, Server Hello Done
-> Client Key Exchange, Change Cipher Spec, Finished
<- Change Cipher Spec, Finished
```

**local-tunnel (mtu 1420):**
```
-> Client Hello
<- Server Hello
<- Certificate, Server Key Exchange, Server Hello Done
-> Client Key Exchange, Change Cipher Spec, Finished
<- Change Cipher Spec, Finished
```

**remote-onetun-server (mtu 1500):**
```
-> Client Hello
<- Server Hello, Certificate
<- Server Key Exchange, Server Hello Done
-> Client Key Exchange, Change Cipher Spec, Finished
<- Change Cipher Spec, Finished
```

**remote-tunnel (mtu 1420):**
```
-> Client Hello
<- Server Hello
<- Certificate, Server Key Exchange, Server Hello Done
-> Client Key Exchange, Change Cipher Spec, Finished
<- Change Cipher Spec, Finished
```

----

My thoughts:

- As far as I can tell, the MTU is the only differentiating factor between loopback and ethernet (since you said you tried adding latency).

- It's possible that the stacking of TLS data within TCP to fit the MTU breaks something later in the connection; maybe it's not able to reconstruct the records if they've been broken up differently by onetun? If that's the case, why does it work with `1420 -> 65536` but not `1420 -> 1500`?

- Some MTU-related features are not implemented in `smoltcp`, like IPv4 fragmentation and PLPMTU. That might affect the `onetun <-> nginx` TCP/IP link somehow, but if that were the case, I think the issue would manifest itself regardless of the server MTU (65536 vs 1500).

**Comment by aramperes** [comment]
Interestingly I was able to fix the issue by reducing the `smoltcp` TCP buffer capacity to match the server MTU (1500): https://github.com/aramperes/onetun/commit/c7af7c472ccd59486d5da0d175f6c96deb5add57. This forces smoltcp to generate smaller frames that can pass through the server MTU down the line.

However, this greatly reduces bandwidth performance, I'll need to investigate more.

**Comment by aramperes** [comment]
The issue seems to be with the advertised MSS differing between onetun's TCP listener and the virtual TCP client.

- TCP listener (ethernet): `MUT-40 == 1500-40 == 1460`
- smoltcp virtual client: `MUT-40 == 1420-40 == 1380`

When `curl` connects to `onetun`, it should receive an advertise MSS of 1380. This can be fixed at the OS level with `ip` but in the spirit of this project, I'll try to use `setsockopt` for `TCP_MAXSEG` to fix this.

**Comment by null-dev** [comment]
Thanks for looking so deep into this issue! Seems like it's quite difficult to debug, I would love to help but I am terrible at networking stuff :cry: .

**Comment by aramperes** [comment]
I'm pretty sure #32 fixes it (I tested with the same setup as given). Turns out, `TcpStream#write` will truncate data if something in the underlying interface fails (which usually happens on big payloads with small MTUs). The fix is just to keep writing!

I'll merge and release shortly.

**Comment by null-dev** [comment]
Works beautifully now, thank you so much!
